name: Create Release

on:
  push:
    tags:
      - v*

jobs:
  test_beforehand:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test CardDeck
        run: /opt/hostedtoolcache/go/1.19.1/x64/bin/go test ./CardDeck -cover -v
      - name: Test Watten
        run: /opt/hostedtoolcache/go/1.19.1/x64/bin/go test ./Watten -cover -v
  build:
    runs-on: ubuntu-latest
    needs: test_beforehand
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build for Linux
        run: /opt/hostedtoolcache/go/1.19.1/x64/bin/go build -o WattenServer/bin/WattenServer ./WattenServer
      - name: Build for Windows
        run: GOOS=windows GOARCH=amd64 /opt/hostedtoolcache/go/1.19.1/x64/bin/go build -o WattenServer/bin/WattenServer.exe ./WattenServer
      - name: ZIP Files
        run: |
          cd WattenServer
          zip -r  watten.zip *.js *.html svg
          zip -jr watten.zip bin
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "WattenServer/watten.zip"
          token: ${{ secrets.GITHUB_TOKEN }}