name: Run Tests

on:
  push:
  workflow_dispatch:

jobs:
  Test_CardDeck_Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: /opt/hostedtoolcache/go/1.18.4/x64/bin/go test ./CardDeck -cover -v
  Test_Watten_Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: /opt/hostedtoolcache/go/1.18.4/x64/bin/go test ./Watten -cover -v
  Test_WattenServer_Build_Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: cd WattenServer; /opt/hostedtoolcache/go/1.18.4/x64/bin/go build
  Test_CardDeck_Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: Start-Process -nonewwindow cd CardDeck; $Env:GOROOT_1_18_X64\bin\go.exe test
  Test_Watten_Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: Start-Process -nonewwindow cd Watten; '$Env:GOROOT_1_18_X64\bin\go.exe test' 
  Test_WattenServer_Build_Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: Start-Process -nonewwindow cd WattenServer; $Env:GOROOT_1_18_X64\bin\go.exe build