name: Run Tests

on:
  push:
  workflow_dispatch:

jobs:
  Test_CardDeck_Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: /opt/hostedtoolcache/go/1.19.*/x64/bin/go test ./CardDeck -cover -v
  Test_Schafkopfen_Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: /opt/hostedtoolcache/go/1.19.*/x64/bin/go test ./Schafkopfen -cover -v
  Test_SchafkopfenServer_Build_Ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: cd SchafkopfenServer; /opt/hostedtoolcache/go/1.19.*/x64/bin/go build
  Test_SchafkopfenServer_Build_For_Windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: cd SchafkopfenServer; GOOS=windows GOARCH=amd64 /opt/hostedtoolcache/go/1.19.*/x64/bin/go build
  Test_SchafkopfenServer_Build_For_MacOS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: cd SchafkopfenServer; GOOS=darwin GOARCH=amd64 /opt/hostedtoolcache/go/1.19.*/x64/bin/go build