name: Run Tests

on:
  push:
  workflow_dispatch:

jobs:
  Test_CardDeck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: cd CardDeck; /opt/hostedtoolcache/go/1.18.3/x64/bin/go test
  Test_Watten:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: cd Watten; /opt/hostedtoolcache/go/1.18.3/x64/bin/go test